import Head from 'next/head'
import Image from 'next/image'
import About from '../sections/About'
import Certification from '../sections/Certification'
import Education from '../sections/Education'
import Experience from '../sections/Experience'
import Organizations from '../sections/Organizations'
import Projects from '../sections/Projects'
import Skills from '../sections/Skills'
import styles from '../styles/Home.module.css'
import { motion, useScroll, useSpring } from "framer-motion";



export default function Home() {
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    // stiffness: 100,
    // damping: 30,
    // restDelta: 0.001
  });


  return (
    <motion.div className={styles.container} >

      <Head>
        <title>Sean Xavier Nieva | Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col">
        <About />
        <Education />
        <Skills />
        <Experience />
        <Certification />
        <Projects />
        <Organizations />
        <motion.div
          initial={false}
          className="progress-bar fixed h-4 bottom-0 left-0 right-0 origin-bottom-left dark:bg-cyan-500 bg-slate-900"
          style={{ scaleX: scrollYProgress }}
        />




      </main>




    </motion.div>
  )
}
