import Head from 'next/head'
import Image from 'next/image'
import Certification from '../sections/Certification'
import Education from '../sections/Education'
import Experience from '../sections/Experience'
import Organizations from '../sections/Organizations'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col">
        <Education />
        <Experience/>
        <Certification/>
        <Organizations/>

      </main>



    </div>
  )
}
